### ISSUE TITLE
Use system variable instead of user name based path

### ISSUE THREAD

**Issue by tywunon** [mykerbal/SoftInc-Modder#1]
I saw you used 
@"C:\Users\" + userName + @"\Desktop..."
but user can set their user profile folder to another than C:\Users<username>.  Consider to use the system variable instead.
@"%UserProfile%\Desktop..."

**Comment by Squalalah** [comment]
kk i will fix it today (or tomorrow, i spent my day to make a dynamic translation system + french translation)
